### ISSUE TITLE
Cant run on windows

### ISSUE THREAD

**Issue by access3424** [stronnag/impload#2]
Hi,
I'm new on github and inav. I'm trying to load some waypoints onto my fc. I downloaded the .exe file for impload but i cant seem to get it to run on windows. please help

**Comment by stronnag** [comment]
Some examples of how it fails would help .... 
What have you tried as far, and how did it fail.

**Comment by access3424** [comment]
well i try to open the .exe file and nothing happens. is it meant to be opened through another program?

**Comment by stronnag** [comment]
you run it in a cmd shell .... it's a command line program.  See the README

**Comment by access3424** [comment]
ok I have it running with powershell but it's still not very clear to me how to connect the flight controller and upload waypoints.

**Comment by stronnag** [comment]
There is a Windows example in the readme. All the other examples are also relevant for Windows, you just have to define the device name as part of the command, for example (upload a GPX file).
```
impload -d COMxx upload file.gpx
```
The flight controller is physically connected to the computer using a USB cable, as one would to flash to use the confgurator (and it's the same device name as used by the configurator).

How are you defining the WPs (which format)?

**Comment by access3424** [comment]
oh shit it worked! thank you very much!

**Comment by stronnag** [comment]
Closed. Non issue.

* There is no need to sound surprised ....
* It would be interesting to know your use case; there are a number of Windows users frustrated by the lack of mission planning options for Windows, so knowing your solution might be helpful to them.
